databases:
  - name: todo_list
    plan: free
    databaseName: todo_list
    user: postgres
    password: root

services:
  - type: web
    plan: free
    name: todo_list
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn todo_list.asgi:application --host 127.0.0.1 --port 8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4